version: '3'

services:
  jg:
    build:
      context: ./janus
      dockerfile: Dockerfile
    volumes:
      - ./janus/conf/:/opt/janus/etc/janus/
    ports:
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "10000-10200:10000-10200/udp"

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - jg
    volumes:
      - "./nginx/certs/cert.crt:/etc/nginx/cert.crt"
      - "./nginx/certs/cert.key:/etc/nginx/cert.key"
      - "./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "443:443"
      - "7989:7989"     # Admin API WebSockets server secure port
      - "8089:8089"     # Web server secure HTTPS port
      - "8989:8989"     # WebSockets server secure port
      - "7889:7889"     # Admin/monitor web server HTTPS port